import { useMemo } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { getMockData } from '../services/dataService'
import { useBoardStore } from '../stores/useBoardStore'
import type { TaskStatus } from '../types'

const statusLabels: { status: TaskStatus; label: string; color: string }[] = [{ status: 'backlog', label: 'Backlog', color: '#c8b58d' }, { status: 'in-progress', label: 'In progress', color: '#5caa9c' }, { status: 'review', label: 'Review', color: '#e1b967' }, { status: 'done', label: 'Done', color: '#8dbd71' }]

export function AnalyticsPage() {
  const { data, isPending, isError } = useQuery({ queryKey: ['mock-data'], queryFn: getMockData })
  const boardTasks = useBoardStore((state) => state.tasks)
  const tasks = useMemo(() => boardTasks.length ? boardTasks : data?.tasks ?? [], [boardTasks, data?.tasks])
  const velocity = useMemo(() => data?.sprints.map((sprint) => ({ name: sprint.name, completed: tasks.filter((task) => task.sprintId === sprint.id && task.status === 'done').length })) ?? [], [data?.sprints, tasks])
  const status = useMemo(() => statusLabels.map((item) => ({ ...item, value: tasks.filter((task) => task.status === item.status).length })), [tasks])
  const priorityByStatus = useMemo(() => statusLabels.map((column) => ({ name: column.label, high: tasks.filter((task) => task.status === column.status && task.priority === 'high').length, medium: tasks.filter((task) => task.status === column.status && task.priority === 'medium').length, low: tasks.filter((task) => task.status === column.status && task.priority === 'low').length })), [tasks])
  const completionTrend = useMemo(() => tasks.filter((task) => task.completedAt).reduce<Record<string, number>>((result, task) => { const date = task.completedAt?.slice(5, 10) ?? ''; result[date] = (result[date] ?? 0) + 1; return result }, {}), [tasks])
  const trend = Object.entries(completionTrend).sort(([first], [second]) => first.localeCompare(second)).map(([date, completed]) => ({ date, completed }))
  if (isPending) return <div className="full-screen-state">Loading analytics...</div>
  if (isError || !data) return <div className="state-panel">Could not load analytics.</div>
  return <main className="workspace"><section className="page-heading"><div><p className="eyebrow">Sprint intelligence</p><h1>Analytics</h1><p className="page-subtitle">Live views derived from your current task data.</p></div></section><div className="chart-grid"><section className="chart-card"><h2>Sprint velocity</h2><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><BarChart data={velocity}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e5ece9" /><XAxis dataKey="name" tickLine={false} axisLine={false} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} /><Tooltip /><Bar dataKey="completed" fill="#398477" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></div></section><section className="chart-card"><h2>Task status</h2><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={status} dataKey="value" nameKey="label" innerRadius={55} outerRadius={85} paddingAngle={3}>{status.map((item) => <Cell key={item.status} fill={item.color} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div><div className="chart-legend">{status.map((item) => <span key={item.status}><i style={{ background: item.color }} />{item.label} {item.value}</span>)}</div></section><section className="chart-card"><h2>Priority breakdown</h2><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><BarChart data={priorityByStatus}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e5ece9" /><XAxis dataKey="name" tickLine={false} axisLine={false} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} /><Tooltip /><Bar dataKey="high" stackId="priority" fill="#c97966" /><Bar dataKey="medium" stackId="priority" fill="#d8a656" /><Bar dataKey="low" stackId="priority" fill="#80a99c" /></BarChart></ResponsiveContainer></div><div className="chart-legend"><span><i style={{ background: '#c97966' }} />High</span><span><i style={{ background: '#d8a656' }} />Medium</span><span><i style={{ background: '#80a99c' }} />Low</span></div></section><section className="chart-card"><h2>Completion trend</h2><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><LineChart data={trend}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e5ece9" /><XAxis dataKey="date" tickLine={false} axisLine={false} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} /><Tooltip /><Line type="monotone" dataKey="completed" stroke="#398477" strokeWidth={3} dot={{ r: 3 }} activeDot={{ r: 5 }} /></LineChart></ResponsiveContainer></div></section></div></main>
}
